/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DRIZZLE_DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DxfElinayApi": {
      "type": "sst.aws.Router"
      "url": string
    }
    "DxfElinayBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DxfElinayJsonParsedBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DxfElinayPreviewBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
